amazonProperties:
  endpointUrl: https://s3.ap-south-1.amazonaws.com
  accessKey: AKIAIFBBBPH6C3KLZYGQ
  secretKey: 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
  bucketName: bhabadyuti-bucket
  
    
spring:
 http:
  multipart:
   max-file-size: 10MB
   max-request-size: 10MB
    